services:
  tomcat:
    build: .
    container_name: project05-tomcat
    ports:
      - "80:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://54.180.102.188:3306/team5_db
      - SPRING_DATASOURCE_USERNAME=team5_user
      - SPRING_DATASOURCE_PASSWORD=team5pass
