spring.application.name=project05
server.servlet.context-path=/project05

# JSP MVC View Resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Character Encoding
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.enabled=true
spring.servlet.encoding.force=true

# MyBatis: u_idx(DB) -> uIdx(Java) 자동 매핑 설정
mybatis.configuration.map-underscore-to-camel-case=true

# Include secret properties
spring.config.import=optional:application-secret.properties
